---
title       : Linear Regression and Moneyball
subtitle    : Unit 2 of MITx 15.071x The Analytics Edge
author      : Summit Suen
job         : Taiwan R User Group
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## RLadies Lightning Talk

### MITx: 15.071x The Analytics Edge

---

## Linear Regression

```{r}
wine <- read.csv(file = "wine.csv", header = TRUE)
model1 <- lm(Price ~ AGST + HarvestRain + Age + FrancePop + WinterRain, data = wine)
summary(model1)
```

---

## Linear Regression

```{r}
model2 <- lm(Price ~ AGST + HarvestRain  + FrancePop + WinterRain, data = wine)
summary(model2)
```

---

## Linear Regression

```{r}
model3 <- lm(Price ~ AGST + HarvestRain  + Age + WinterRain, data = wine)
summary(model3)
```

---

## Linear Regression

```{r}
model4 <- lm(Price ~ HarvestRain+ WinterRain, data = wine)
summary(model4)
```
